name: create-manual
author: gendloop
description: 'create manual for folder'
inputs:
# Required
  folder:
    description: 'Folder to use'
    required: false
    default: 'tests'
  destination:
    description: 'Destination to output'
    required: false
    default: 'docs'

runs:
  using: 'composite'
  steps:
    - name: create-manual
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: |
        ${{ github.action_path }}\tools\ManualCreate_exe.exe ${{ inputs.folder }} _temp
        Rename-Item _temp\tests.md Manual.md
        Copy-Item _temp\* ${{ inputs.destination }} -Recurse -Force
        Remove-Item _temp\* -Recurse

    - name: git-push
      uses: gendloop/git-push@v1.0.0
      with:
        token: ${{ github.token }}
        commit: "chore: create manual for \\`${{ inputs.folder }}\\` and export to \\`${{ inputs.destination }}\\` "
