name: Create_Manual

permissions:
  contents: write
  actions: write

on: 
  workflow_dispatch:
  schedule:
    - cron: '40 16 * * *'

jobs:
  create_manual:
    runs-on: ubuntu-latest
    steps:
      - name: create-manual
        uses: gendloop/create-manual@main
      